function testArticle(){
    // window.DEBUG = true;

    //ready
    //setBody & parse
    var bodyStr = '<div id="article">'
                + '    <h1><a href="http://zx.youdao.com/zx/archives/5890" title="有一些方面，老美其实比国人更保守">有一些方面，老美其实比国人更保守</a>'
                + '    </h1>'
                + '    <div class="info">'
                + ''
                + '    </div>'
                + '    <div class="text">'
                + '        <p>'
                + '            <a href="http://126.am/OLKdt3">'
                + '                <img src="http://zx.youdao.com/zx/wp-content/uploads/2013/10/42.640_520.jpg" alt="42.640_520" width="640" height="520" class="aligncenter size-full wp-image-5892">'
                + '            </a>'
                + '        </p>'
                + '        <p>文 | acel rovsion 图 | Anthony Quintan(CC BY)</p>'
                        + '<p>在很多人看来，欧美的人们比较“开放”，而亚洲人则是传统和保守的代名词。其实在某些方面，实则美国远比中国要保守（指现代文化），我对美国相对比较熟悉，就以个人观察来比较下中美吧。有以下8个方面，美国人会比中国人保守的——</p>'
                        + '<p>第一，婚姻观和家庭观。美国人的婚姻观在严格的婚姻相关法律和清教徒的品性下，对于婚姻的要求实际上是极为简单和保守——双方忠诚，平和的生活，孩子，共同奋斗的家产。用一个比较土的描述就是标准的老婆孩子热炕头吃喝不愁型的，当然妇女运动过后，女性在家庭中的角色也并非兼职主妇，男性也基本上除了工作，少许社交，也就是自觉陪老婆的节奏，总来看基本上家庭观和生活方式相当保守。对换到中国家庭观来，这基本上只能算基本配备而绝不是全部。</p>'
                + '        <p>第二，对于宗教的态度。基本上来说，美国大部分人即使不信教，也难以摆脱对上帝的敬畏感。就国内而来，我们的无神论的比例是要高出许多的。</p>'
                        + '<p>第三，对于女性“性骚扰”的问题。国内而言，职场上，对于同事女性不论是聊天也好，还是合作也好，只要符合礼貌规范，基本上不会出现什么大问题。但是呢，“性骚扰”在70年代第二次女权主义运动后，被搞成了至今为止都非常敏感的一个事情。举个例子，我认识一位姐姐在纽约某医工企业做销售，其人长得算是比较漂亮的。有一次，她换了新的造型和职业套装去上班，正常情况下，在国内，如果老板看到，称赞一句，XX今天很漂亮。我们会觉得是一件没有什么太大问题的事情。但是，这位美国上司带着无比纠结的表情地称赞“你今天看起来比较不同。”</p>'
                        + '<p>第四，种族问题。种族问题一直比较敏感，而且民间的态度激进分子不少。但是在公开场合的情况下，尤其是政治场合的情况下，种族问题是尽量不要“认真”地去在“公开平台”上讨论，当然脱口秀上调侃一下还是可以的，现在也没有到如此禁锢的地步。这种事情在中国基本上不常见。</p>'
                        + '<p>第五，女权主义者。美国在70年代二次妇女运动之后，基本上摒弃了一代妇女运动时期所贯彻的一些女权运动的一些手法，比如女权主义战线政治化。取而代之的是新女权主义，左派女权主义和右派女权主义，在新的所谓“妇女运动”中，强调的更多是女性意识的独立。</p>'
                        + '<p>第六，个人生活的隐私感。在国内，比较好的朋友之间，尤其是互相亲戚还认识的情况下，聊天的时候，触及到一些家庭琐事，自家家里的一些八卦，都是可以拿来分享的。但是老美聊天是非常泛的，很少可以去触及这一块的领域，虽然不是刻意的防范，但总归不是很乐意去聊一些家里的事情，也不是特别乐意别人对自己家庭有一些建议。</p>'
                        + '<p>第七，饮食方面。美国虽然有全世界最会做饭的民族，华人，法国人，日本人，意大利人带去的美食，让美国大城市的餐馆事实上口碑都不错。但是本土的美国教徒是对食物比较保守的，比如吃鸡主要吃鸡胸，对内脏比较受不了，等等。</p>'
                        + '<p>第八，个人政治言论。其实美国人对政治的热情和关注度比不上中国人。但是政治说到底也是主要话题之一，但是与犀利吐槽的美国脱口秀不同。。普通美国人在政治立场上往往有一种“老好人”情结，只当生活的调剂，除了专业的政治活动家，很少普通人会去因为政治立场，非得和人家从针锋相对到对喷。基本态度是，我倾听你，我坚持自己，但是我不会去刻意说服你。</p>'
                + '        <p style="text-align: center;"><a href="http://www.zhihu.com/question/20482050">【查看更多讨论】</a>'
                + '        </p>'
                + '        <p>「知天下」栏目内容精选自<a href="http://126.am/9AdYi4">知乎日报[点此下载]</a>，并授权有道词典转载发布；二次转载请注明作者和源讨论地址。</p>'
                + '        <div id="watch_action">'
                + '            <div id="watch_position" style="float:left; ">'
                + '                <div id="action_like">'
                + '                    <span class="like">'
                + '                        <img title="顶" id="like" rel="like" pid="5890" class="lbg-style1 jlk" src="http://zx.youdao.com/zx/wp-content/plugins/wti-like-post/images/pixel.gif">'
                + '                    </span>'
                + '                    <span id="lc" class="lc">410</span>'
                + '                </div>'
                + '                <div id="action_unlike">'
                + '                    <span class="unlike">'
                + '                        <img title="踩" id="unlike" rel="unlike" pid="5890" class="unlbg-style1 jlk" src="http://zx.youdao.com/zx/wp-content/plugins/wti-like-post/images/pixel.gif">'
                + '                    </span>'
                + '                    <span id="unlc" class="unlc">71</span>'
                + '                </div>'
                + '            </div>'
                + '            <div id="status" class="status" style="float:left; ">&nbsp;&nbsp;</div>'
                + '        </div>'
                + '        <div id="clear"></div>'
                + '    </div>'
                + '    <div class="text_add">'
                + '        <div class="copy">'
                            + '<p style="color: #777; font-size: 12px;">本文由有道词典原创或授权发布，转载请注明出处和链接，<a style="color:#049" href="/zx/feedback">如有问题，点此反馈</a>'
                + '            </p>'
                + '        </div>'
                + '        <div class="share"></div>'
                + '    </div>'
                + '</div>';

    var type = 'article';
    var data = BASE64.encode(window.JSON.stringify([bodyStr, type]));
    var result = window.Js.setBody(data);
    //send body
    document.body.innerHTML = result;
    
    // window.DEBUG = false;
}

function testWord(){
    // window.DEBUG = true;

    //ready
    //setBody & parse
    var bodyStr = '<div class="title grey">基本释义</div>'
                + '    <div class="trans-container ce">'
                + '        <ul>'
                + '            <li>'
                + '                <a class="clickable" href="link:in">in</a>'
                + '                <a class="clickable" href="link:regard">regard</a>'
                + '                <a class="clickable" href="link:to">to</a>'
                + '            </li>'
                + '            <li>'
                + '                <a class="clickable" href="link:as">as</a>'
                + '                <a class="clickable" href="link:regards"> regards </a> '
                + '            </li>'
                + '            <li>'
                + '                <a class="clickable" href="link:with"> with </a>'
                + '                <a class="clickable" href="link:respect"> respect </a>'
                + '                <a class="clickable" href="link:to"> to </a>'
                + '            </li>'
                + '        </ul>'
                + '    </div>'
                + '    <div class="title grey">现代汉语大词典</div>'
                + '    <div class="trans-container hh">'
                + '        <h4>'
                + '            关于'
                + '            <span class="grey">[guān yú]</span>'
                + '        </h4>'
                + '        <ul>'
                + '            <li class="mcols-layout">'
                + '                <span class="col1 secondary">1.</span>'
                + '                <div class="col2">'
                + '                    <p>关系到。</p>'
                + '                    <p class="secondary">朱自清《论老实话》：“真话不一定<b>关于</b>事实，主要的是态度。”</p>'
                + '                </div>'
                + '            </li>'
                + '            <li class="mcols-layout">'
                + '                <span class="col1 secondary">2.</span>'
                + '                <div class="col2">'
                + '                    <p>介词。</p>'
                + '                </div>'
                + '            </li>'
                + '            <li class="mcols-layout">'
                + '                <span class="col1 secondary">3.</span>'
                + '                <div class="col2">'
                + '                    <p>$引进某种行为的关系者，组成介词结构做状语。</p>'
                + '                    <p class="secondary">鲁迅《致唐弢》：“来信问我的几件事情之中，<b>关于</b>书籍的，我无法答复。”</p>'
                + '                </div>'
                + '            </li>'
                + '            <li class="mcols-layout">'
                + '                <span class="col1 secondary">4.</span>'
                + '                <div class="col2">'
                + '                    <p>$引进某种事物的关系者，组成介词结构做定语（现代汉语后面要加“的”）。</p>'
                + '                    <p class="secondary">巴金《寒夜》：“无论如何，向父亲告别的时候，小宣应该问一句<b>关于</b>妈的话。”</p>'
                + '                </div>'
                + '            </li>'
                + '            <li class="mcols-layout">'
                + '                <span class="col1 secondary">5.</span>'
                + '                <div class="col2">'
                + '                    <p>现代汉语也在“是…的”式中做谓语。</p>'
                + '                    <p class="secondary">今天在厂里开了一个会，是<b>关于</b>爱国卫生运动的。</p>'
                + '                </div>'
                + '            </li>'
                + '        </ul>'
                + '        <p class="secondary source">以上来源于：《现代汉语大词典》</p>'
                + '    </div>'
                + '    <div class="title grey">新汉英大词典</div>'
                + '    <div class="trans-container ce_new">'
                + '        <h4>'
                + '            关于'
                + '            <span class="grey">[guān yú]</span>'
                + '        </h4>'
                + '        <ul>'
                + '            <li class="per-tran">'
                + '                <span class="grey"></span>'
                + '                <ul class="trans-list">'
                + '                    <li class="mcols-layout">'
                + '                        <span class="col1 secondary">1.</span>'
                + '                        <div class="col2">'
                + '                            <span>about; on; with regard to; concerning; in regard to [of]; with respect to; as respects; as regards; in this regard; in one regard; as concerns ...; as to; relate to ...; in relation to; relative; as far as ... be concerned:</span>'
                + '                            <p class="secondary">'
                + '                                regulations concerning the protection of forests; &nbsp;/&nbsp;关于保护森林的若干规定'
                + '                            </p>'
                + '                            <p class="secondary">'
                + '                                international legislation on shipping; &nbsp;/&nbsp;关于航运的国际立法'
                + '                            </p>'
                + '                        </div>'
                + '                    </li>'
                + '                </ul>'
                + '            </li>'
                + '        </ul>'
                + '        <p class="secondary source">以上来源于：新汉英大辞典</p>'
                + '</div>';

    var type = 'word';
    var data = BASE64.encode(window.JSON.stringify([bodyStr, type]));
    var result = window.Js.setBody(data);
    //send body
    document.body.innerHTML = result;
    // window.DEBUG = false;
}